paths: 
  /api/products/:
    get:
      summary: Obtiene todos los productos disponibles en la aplicación
      tags:
        - Products
      responses:
        "200":
          description: La operación fue exitosa. Se retorna el arreglo con los productos.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Products'

        "500":
          description: Error inesperado en el server, no se puede manejar el proceso.
        "401":
          description: Usuario no está autenticado.
    post:
      summary: Crea un nuevo producto
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/NewProduct'
      responses:
        "201":
          description: El producto ha sido creado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
        "400":
          description: El producto ya existe / Falta uno o más campos

  /api/products/{pid}:
    get:
      summary: Obtiene un producto a través del id ingresado
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        description: Parámetro con el id del producto
        required: true
        type: string
      responses:
        "200":
          description: El producto cuyo id coincide con el que se ha ingresado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
        "404":
          description: El producto no ha sido encontrado
    put:
      summary: Actualiza un producto
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        description: Parámetro que toma el id del producto
        required: true
        type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/NewProduct'
      responses:
        "200":
          description: El producto se actualizó.
          content:
            application/json:
              schema:
                $ref: '#/components/requestBodies/NewProduct'
        "400":
          description: El producto no ha sido encontrado / Falta uno o más campos

components:
  schemas:
    Products: 
      type: object
      properties:
        _id: 
          type: ObjectId
          description: Id autogenerado de MongoDB.
        title: 
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripción del producto
        code:
          type: Number
          description: Código del producto
        price:
          type: Number
          description: Precio del producto
        status:
          type: Boolean
          description: Status del producto
        stock:
          type: Number
          description: Número de productos disponibles en stock
        category:
          type: String
          description: Categoría a la que pertenece el producto
        thumbnail:
          type: Array
          description: Enlaces con miniaturas de imágenes del producto
        owner:
          type: String
          description: Idetificador del usuario que agregó el producto     
      example: 
        _id: ObjectId("647fa8c9e46dbc5a20320181")
        title: Producto de prueba 1
        description: Descripción de prueba 1
        code: 213414514
        price: 234
        status: true
        stock: 30
        category: Categoría de prueba 1
        thumbnail: []
        owner: admin
  requestBodies:
    NewProduct:
      type: object
      required:
        - nombre
        - precio
      properties:
        title:
          type: String
          description: Título del producto.
        description:
          type: String
          description: Descripción del producto.
        code:
          type: Number
          description: Código del producto
        price:
          type: Number
          description: Precio del producto
        status:
          type: Boolean
          description: Status del producto
        stock:
          type: Number
          description: Cantidad de unidades del producto en el stock
        category:
          type: String
          description: Categoría en que la que el producto está clasificado
        thumbnail:
          type: Array
          description: Colección de enlaces de las miniaturas del producto
      example: 
        title: Producto de prueba 1
        description: Descripción de prueba 1
        code: 213414514
        price: 234
        status: true
        stock: 30
        category: Categoría de prueba 1
        thumbnail: []

